### ISSUE TITLE
Add an option to only list peer dependencies

### ISSUE THREAD

**Issue by sschuberth** [spatie/npm-install-peers#11]
It would be useful if there was an option to list the declared peer dependencies (in a machine readable format like JSON) without actually installing them. This is similar to my [npm feature request](https://github.com/npm/npm/issues/17661) to extend `npm list` to support `--only=peer`, but even if implemented that would only work for already installed peer dependencies.

**Comment by sebastiandedeyne** [comment]
This package installs the peer dependencies of the current project, what you're proposing is listing the peer dependencies of your project's dependencies, no?

In that case, it's outside of the scope of this project. In the other case, I don't really see the point since that data already exists in your package.json.

**Comment by sschuberth** [comment]
> what you're proposing is listing the peer dependencies of your project's dependencies, no?

No. What I'm interested in is the list of first-order peer dependencies and their (transitive) production dependencies. Sure that data already is available in (a collection of remotely available) `package.json` files, but this whole tool is about convenience. Otherwise I could have also used a combination of `jq`, `xargs` and `npm install` to install peer dependencies.

Anyway, I guess you could have waited for my reply instead of closing this prematurely 😞
